# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=datetime.datetime(2018, 5, 29, 8, 26, 50, 586883))),
                ('notes', models.CharField(blank=True, max_length=256)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('invoice_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime(2018, 4, 29, 8, 26, 50, 587460))),
                ('due_date', models.DateField(default=datetime.datetime(2018, 5, 29, 8, 26, 50, 587481))),
                ('charge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.AccountReceivable')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=48)),
                ('phone_number', models.CharField(blank=True, max_length=48)),
                ('address', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('invoice_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=datetime.datetime(2018, 4, 29, 8, 26, 50, 587956))),
                ('payment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.AccountReceivable')),
            ],
        ),
        migrations.CreateModel(
            name='TireInvBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TireInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('supplier_code', models.CharField(choices=[(b'ATD', b'ATD'), (b'FT', b'FT'), (b'RR', b'RR')], max_length=16)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.TireInvBrand')),
            ],
        ),
        migrations.CreateModel(
            name='TireInvSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TireSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(default=datetime.datetime(2018, 4, 29, 8, 26, 50, 586210))),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.IntegerField()),
                ('mileage', models.IntegerField(blank=True, default=0, null=True)),
                ('rotation_performed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.Customer')),
                ('tires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.TireInventory')),
            ],
        ),
        migrations.AddField(
            model_name='tireinventory',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.TireInvSize'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conoco.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='tireinventory',
            unique_together=set([('size', 'brand', 'supplier_code')]),
        ),
    ]
